### ISSUE TITLE
Noetic Release

### ISSUE THREAD

**Issue by tlpss** [ros-perception/slam_gmapping#94] opened 2020-08-06 12:54 UTC
Are there any plans for a release for ROS Noetic?

**Comment by k-okada** [comment] 2020-08-09 03:15
@mikeferguson I think we need to remove `signal` from `find_package(Boost ` for noetic https://github.com/ros-perception/slam_gmapping/pull/84/commits/1f6be646e1d33a0cc2e3f2eec16c25396f72a56b

I have confirmed this with https://travis-ci.com/github/k-okada/slam_gmapping

**Comment by Tobias-Fischer** [comment] 2020-09-04 00:28
Ping :)

**Comment by tonybaltovski** [comment] 2020-10-01 15:51
+1

**Comment by mikeferguson** [comment] 2020-10-01 16:04
This package actually doesn't have a maintainer (it's on the orphaned packages list). I did the last release just because I had access it appeared to be a clear regression that had been merged. If someone wants to step up and take over maintaining, that'd be the fastest way to get this released.

**Comment by tonybaltovski** [comment] 2020-10-01 16:18
I could volunteer to maintain it to get a release out but I feel like there might better maintainers.

**Comment by k-okada** [comment] 2020-10-02 01:16
ok, done. released https://github.com/ros/rosdistro/pull/26787 as a part of orphaned initiatives (https://github.com/ros-infrastructure/rep/pull/150)

@mikeferguson could you enable TravisCI and "request up to date before merging" (
https://docs.github.com/en/free-pro-team@latest/github/administering-a-repository/types-of-required-status-checks )

Or give me a full access to this reository so that I can control this and invite other people as a maintaner.

**Comment by mikeferguson** [comment] 2020-10-02 01:44
@k-okada you should now be an admin of this and the other gmapping repos

**Comment by k-okada** [comment] 2020-10-02 01:47
@mikeferguson thank you ! , could you also enable https://travis-ci.com/github/ros-perception/slam_gmapping ?

**Comment by mikeferguson** [comment] 2020-10-02 02:53
In theory I just did - let me know if it works now (I'm not 100% since they are like mid-migration of how things connect)

**Comment by k-okada** [comment] 2020-10-02 03:17
@mikeferguson thank you , everything working fine https://travis-ci.com/github/ros-perception/slam_gmapping/builds/187738838

**Comment by mikeferguson** [comment] 2020-10-11 13:12
https://github.com/ros/rosdistro/pull/26787

**Closed as completed by mikeferguson** 2020-10-11 13:12 UTC
